### PR TITLE
Feature/homepage repository - Add catalog component to homepage

### PR DESCRIPTION
**Pull request by AmbyrElan**
## Reason for change

- Making an example test for a custom controller using components
- FYI for reviewers- In a future iteration and in effort to reduce the probability of an altered core Base file, we will eventually replace "Homepage" with "Custom" and convert it to stub data to be used with php artisan base:feature. This PR is an important step on that journey to also include a foundational test file to begin using for the custom template. 
- [feat: add catalog component to homepage styleguide](https://github.com/waynestate/base-site/commit/e7bf35e29cd829376d664a0a42cbb79246b45b5d)
- [chore: composer update](https://github.com/waynestate/base-site/commit/8a7e28b1ea76e557ccd33274959b5f57bebbd26a)
- [fix: remove unnecessary code](https://github.com/waynestate/base-site/commit/924de479002616562902474da7fa8b3b7e5db152)
- [feat: update homepage to accept array & update test case](https://github.com/waynestate/base-site/commit/529d961a066b7606730cc5d69028dcddd4364fab)

## Screenshots / Videos

| Before  | After |
| ------------- | ------------- |
|||

### CODE REVIEW

**Comment by nickdenardis** [comment]
This says "WIP", is this ready for review? It needs a bit more code coverage.

**Comment by AmbyrElan** [comment]
> This says "WIP", is this ready for review? It needs a bit more code coverage.

This is labeled WIP for work in progress since there is more to be done to get back to 100% code coverage. 
image

**Comment by breakdancingcat** [comment]
@nickdenardis Thanks for looking out. 

Ambyr and I used part of our 1:1 to get her started making changes to Base, and I asked her to make a PR in the mean time so we can easily talk about the changes together.

**Comment by nickdenardis** [comment]
@breakdancingcat @AmbyrElan 
Thanks for the clarification. In GitHub, let's make this a draft PR when it isn't ready for review yet:

Screenshot 2024-05-03 at 9 22 19 AM

**Comment by AmbyrElan** [comment]
- Test coverages have been updated to cover the Homepage controller and are passing now. 
- [fix: test coverage for homepage controller](https://github.com/waynestate/base-site/pull/715/commits/12b0afa18dd237b0639ce3450795274dec0b4b4a)

image

**Review by breakdancingcat — APPROVED** [review]

**Pull request closed without merging**
