### PR TITLE
Contact footer update

### PR DESCRIPTION
**Pull request by breakdancingcat**
Removing the widths on the footer columns so that we can have four or more columns. Sometimes clients want four columns with links, resources etc. This provides flexible scaling without defined widths. After all, that's the perk of flexbox!

### CODE REVIEW

**Comment by nickdenardis** [comment]
What does this look like before and after?

**Comment by robertvrabel** [comment]
Should we change `/config/base.php` to limit 4 instead of 3 by default with this update?

```
    'global_promos' => [
        'main' => [
            'contact' => [
                'id' => 2908,
                'config' => 'limit:3',
            ],
```

**Comment by breakdancingcat** [comment]
@nickdenardis  The screenshots are in the ticket, but @robertvrabel had mentioned not including links to the tickets since this is public. I tagged you in the ticket so you should have an email. #83447

**Comment by breakdancingcat** [comment]
@robertvrabel Updated the config to 4. OK to merge?

**Comment by robertvrabel** [comment]
@breakdancingcat I checked out the branch locally and looks good to me 👍

**Comment by nickdenardis** [comment]
@breakdancingcat 
Because this is public the screenshots attached to each PR would be needed for a public record of each change.

I know they are not needed in every PR, but I have found them helpful in others like:  
https://github.com/waynestate/base-site/pull/275
https://github.com/waynestate/base-site/pull/274
https://github.com/waynestate/base-site/pull/262
https://github.com/waynestate/base-site/pull/261

**Comment by breakdancingcat** [comment]
Screenshots!
footer-desktop
footer-medium-2
footer-mobile

**Pull request closed without merging**
