### PR TITLE
Feature/policy numbering 

### PR DESCRIPTION
**Pull request by AmbyrElan**
Policy numbering was throwing a stylelint error.  
After pulling in develop/master branches, the policy-numbering class was in its own scss file as well as the content scss file.  

- Removed policy-numbering class from content scss class 
- Ran the linter again and the tests passed.
- Tested the code on the front end and it is working when adding the policy-numbering class to the `<ol>` attr.

image

```
<ol class="policy-numbering">
	<li>This will begin the section heading 1.0</li>
	<li>This will begin the section heading 2.0</li>
	<li>This will begin the section heading 3.0
	<ol>
		<li>Sub section 3.1 begins</li>
		<li>Sub section 3.2 begins</li>
		<li>Sub section 3.3 begins
		<ul>
			<li>Sub section a. begins</li>
			<li>Sub section b. begins
			<ul>
				<li>Sub section i. begins</li>
				<li>Sub section ii. begins</li>
			</ul>
			</li>
		</ul>
		</li>
	</ol>
	</li>
</ol>
```

|Mobile|Desktop|
|---|---|
|image|image|

### CODE REVIEW

**Comment by nickdenardis** [comment]
@AmbyrElan 
Perhaps your report may have been out of date, the policy numbering was removed from the main content file in this PR:
https://github.com/waynestate/base-site/pull/725/files

This needs some visual work before it can be put into a release. Let's work that out in Basecamp and then put in another PR once it is complete.

**Comment by AmbyrElan** [comment]
> @AmbyrElan Perhaps your report may have been out of date, the policy numbering was removed from the main content file in this PR: https://github.com/waynestate/base-site/pull/725/files
> 
> This needs some visual work before it can be put into a release. Let's work that out in Basecamp and then put in another PR once it is complete.

@nickdenardis , after fetching and pulling develop, the policy numbering class was still in the content scss file and threw the same errors for me that you showed for  why you pushed the update to deactivate the feature but it seems to be fixed on my end now.  

I updated the example with more text and re-ran the linter.  Everything is checking out on my end.  I'm putting updated screenshots in the PR description.

**Review by nickdenardis — APPROVED** [review]
Looks good 👍

**Comment by breakdancingcat** [comment]
👍 Thanks!

**Pull request merged**
