### PR TITLE
Laravel 10.x Shift

### PR DESCRIPTION
**Pull request by anthonywayne**
This pull request includes the changes for upgrading to Laravel 10.x. Feel free to commit any additional changes to the `shift-97916` branch.

**Before merging**, you need to:

- Checkout the `shift-97916` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by anthonywayne** [comment]
:information_source: Shift noticed you have additional namespaces in your application. You may use the [Consolidate Namespaces Shift](https://laravelshift.com/laravel-consolidate-custom-namespaces) to simplify your namespaces into the default Laravel `App` namespace.

**Comment by anthonywayne** [comment]
:information_source: Laravel 9 moved the `resources/lang` folder to the top level of the project. While Shift moved and replaced references to this folder, you may have additional references to this folder which need to be updated.

**Comment by anthonywayne** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/waynestate/base-site/pull/641/commits/df5eb15d62c2af171cddfbd4429a0b0e49fbfe7d?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert df5eb15d` and make the [config file changes](https://github.com/laravel-shift/laravel-9.x/pull/4/commits/5401110f1f41793ecdce268495768abfa4a53dfe) manually.

**Comment by anthonywayne** [comment]
:information_source: Shift [updated your dependencies](https://github.com/waynestate/base-site/pull/641/commits/ade217c41f5199c92b546a6f3a0424b8ec88c1b0?w=1) for Laravel 10. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 10. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

**Comment by anthonywayne** [comment]
:information_source: Shift detected your application has a test suite. To make verifying the upgrade to Laravel 10 easier, Shift did not upgrade your test suite to PHPUnit 10. Once you have completed your upgrade, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free to upgrade your test suite to PHPUnit 10 separately.

**Comment by anthonywayne** [comment]
:information_source: Laravel 10 added PHP type hints to all user-land code included in a new Laravel application. In an effort to modernize your code, Shift [added type hints](https://github.com/waynestate/base-site/pull/641/commits/6071686386f3c737b31c3472f5830f7d501249b6?w=1) to any method which is used by Laravel.

**Comment by anthonywayne** [comment]
:information_source: Now with type hints in your code, defining types within PHP DocBlocks is redundant. Laravel has removed all of the `@param` and `@return` tags from its DocBlocks where types are defined with PHP. Similarly, Shift [removed these tags](https://github.com/waynestate/base-site/pull/641/commits/709c51b3dff2611ca7460d8bc317afa251f7370f?w=1) from any DocBlock where the code now has _equivalent_ type hints.

**Comment by anthonywayne** [comment]
:information_source: Shift understands developers have different preferences when it comes to type hints. All of Shift's automation is done in nice, atomic commits. This makes it easier to undo any of the changes Shift makes.

If you wish to undo the changes relating to type hints, you may run:

- `git revert 709c51b` to revert the DocBlock changes.
- `git revert bb35979` to revert the type hints added from DocBlocks.
- `git revert 6071686` to revert the type hints added for Laravel 10.

**Comment by anthonywayne** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 6.2. Shift detected references to Symfony classes within your application. You should review the [Symfony change log](https://github.com/symfony/symfony/blob/6.2/UPGRADE-6.2.md) for any additional changes.

**Comment by anthonywayne** [comment]
:information_source: The `app/Models` folder was reintroduced in Laravel 8. This was an _optional_ change. Laravel and the `artisan` commands will automatically detect if you are using the `app/Models` folder or not.

If you wish to modernize your application to use the `app/Models` folder, you may run the [Namespace Models Shift](https://laravelshift.com/laravel-namespace-models) for free.

**Comment by anthonywayne** [comment]
:information_source: Laravel began using Vite to build frontend assets in Laravel 9.19. While you may continue to use Laravel Mix, it is no longer the default. If you wish to modernize your application to use Vite, you may run the [Vite Converter](https://laravelshift.com/convert-laravel-mix-to-vite) for free.

**Comment by anthonywayne** [comment]
:warning: Shift detected your application contains stub files. With all of the type hints added in Laravel 10, you should review these files and add any type hints you want to have when generating classes with `artisan make`.

**Comment by anthonywayne** [comment]
:warning: Laravel 10 requires Composer 2.2 or higher. You should verify the Composer version in your environments by running `composer --version` to ensure it meets this new requirement. If necessary, run `composer self-update` to update Composer.

**Comment by anthonywayne** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel and PHP applications.

**Comment by nickdenardis** [comment]
@waynestate/wayne-state-web-team This is now ready to review.

This Shift upgrade to Laravel 10 was smooth as butter. The only things to note:

- Manually synced the function signatures in the tests to match the contracts
- Added additional info to the profile Factory for the current semester courses
- Fixed the YouTube Video tests to bring code coverage back to 100%

| Output | Tests |
|--------|--------|
| Screenshot 2023-08-16 at 6 11 07 PM | Screenshot 2023-08-16 at 6 14 17 PM |

**Pull request merged**
