### PR TITLE
Update styleguide.blade.php

### PR DESCRIPTION
**Pull request by krystosch**
Added a little more context to headings and fixed a typo.

### CODE REVIEW

**Review by nickdenardis — APPROVED** [review]
👍

**Comment by nickdenardis** [comment]
Should we at least have a reference to the `h1` tag should not be used since the page title is already the H1 on the page?

**Comment by krystosch** [comment]
That would be helpful, just so they know it exists and that the style of it is already in place. @breakdancingcat - thoughts?

**Comment by breakdancingcat** [comment]
@krystosch Yes, can you change it to something like h1 is the page title which is already on each page so headings for your page will be h2-h4.

**Pull request closed without merging**
