### PR TITLE
Feature/hero bgcolor

### PR DESCRIPTION
**Pull request by breakdancingcat**
Added padding to hero text and darkened the bgcolor

### CODE REVIEW

**Comment by breakdancingcat** [comment]
screencapture-base-site-wayne-local-styleguide-hero-contained-text-link-1516289270599
screencapture-base-site-wayne-local-styleguide-hero-contained-text-link-1516289277721

**Comment by tomkrupka** [comment]
Looks good!

**Comment by breakdancingcat** [comment]
Removed margin below hero with rotate_arrows 

screenshot

**Comment by nickdenardis** [comment]
My feeling on the arrow placement (although I totally understand why it is this way) is they look off balance when there is text overlaying the image. My eye wants them to be centered above the copy block instead of closer to the copy block.

But it would totally be different with a real photo.

**Comment by nickdenardis** [comment]
Was this deleted in favor of a different branch or is this feature no longer going to happen?

**Comment by breakdancingcat** [comment]
@nickdenardis I merged it in with the command line. I'm not sure why it says closed.

**Comment by nickdenardis** [comment]
https://github.com/waynestate/base-site/network
I see now that it was merged. 

My bad reading the status messages, the term "deleted" threw me off. 😛

**Pull request closed without merging**
