### PR TITLE
banner text color change

### PR DESCRIPTION
**Pull request by Fw7424**
Changing the banner color in base to resolve color contrast issues. 
example of error in site-improve.

https://my2.siteimprove.com/Accessibility/604878/Pages/Issue?CheckId=20&CriterionChapter=1.4.6

### CODE REVIEW

**Comment by nickdenardis** [comment]
What was the color of the text before? Black?

Have a before and after screenshot?

**Comment by breakdancingcat** [comment]
> What was the color of the text before? Black?
> 
> Have a before and after screenshot?

@nickdenardis  The link color was #0c5449 and the hover was black. This makes the link color green-darker which provides enough contrast, and the hover goes to darkest.

**Comment by breakdancingcat** [comment]
Once you remove hover:text-black you're all set!

**Comment by nickdenardis** [comment]
> > What was the color of the text before? Black?
> > Have a before and after screenshot?
> 
> @nickdenardis The link color was #0c5449 which does not pass contrast and the hover was black. This makes the link color green-darker which provides enough contrast, and the hover goes to green-darkest.

Thanks! Interesting that this didn't get caught in the manual audit. Unless we didn't have the flag as part of that mix of pages.

**Pull request closed without merging**
