### PR TITLE
Release 8.12.0 - Profile titles, base:module command, heading dividers and breadcrumb spacing

### PR DESCRIPTION
**Pull request by nickdenardis**
### [Allow line breaks only in the Title profile field](https://github.com/waynestate/base-site/pull/738)

We are already allowing linebreaks in the Title field on the main university directory, we should allow it on the individual sites to match.

This change allows `<br>` tags only in the Title field.

### [base:module command line now in place](https://github.com/waynestate/base-site/pull/734)

As more functionality on sites is moving to the modular components instead of full templates, this change introduces the `php artisan base:module {name}` command line interface to generate the scaffolding for new modular components.

It works similarly to the `base:feature` and introduces a new "Site specific" menu item in the styleguide to ensure the site-specific modular components are isolated and do not slow down future codebase upgrades.

The stub component intentionally does not do anything other than dump the promotion items and config to the screen.

The "Site specific" styleguide page walks through the process of creation and the next steps to update the styleguide pages with description, config and instructions.

### [Dividers - adjust padding on heading dividers](https://github.com/waynestate/base-site/pull/732)

Updates the position of the header dividers to be more aligned to the center of the words. 

### [Prevent breadcrumbs from running into the Flag](https://github.com/waynestate/base-site/pull/735)

Updates to the placement of the breadcrumbs and flag component. They no longer run into each other.

### [Upgrade stylelint from v13 to v16](https://github.com/waynestate/base-site/pull/741)

Maintenance update for this dependency.

### [Setting the base page controller data to array.](https://github.com/waynestate/base-site/pull/740)

Ensuring the `hero` modular component correctly updates the full width controller 

### [Default back to profiles link now returns 200 response](https://github.com/waynestate/base-site/pull/737)

Updates the URL structure of the default "profile_return_url" from "/profiles/" to "/profiles" because we automatically remove the trailing slash. This reduces an unnecessary redirect.

### [Individual profile name now showing correctly as the page title](https://github.com/waynestate/base-site/pull/736)

Fixes a bug that prevented the full profile user name on the individual profile view. This was introduced in 8.11.0 and is now corrected.

### [Tests passing again after generating a new feature](https://github.com/waynestate/base-site/pull/733)

Due to the changing structure of the childpage, after generating a `base:feature` the tests would immediately fail. This change resolves that issue.

### CODE REVIEW

**Comment by chrispelzer** [comment]
I added the `make stylelintfix` even though it seems odd. Our current set up is using hooks with the dry being `make stylelint` which our hook is using `make phplintdry`

This keeps it in line with our phplint and hooks.
https://github.com/waynestate/base-site/blob/master/hooks/pre-commit#L68

**Comment by nickdenardis** [comment]
@chrispelzer 
Let's keep it to these two commands so it matches the others:

```
make stylelintdry 
make stylelint
```

`make stylelintdry` - Doesn't have the --fix
`make stylelint` - Does have --fix 

This does then change the default behavior of `make stylelint` but it makes it consistent with the other commands.

**Comment by nickdenardis** [comment]
@chrispelzer 
If it affects the user experience of the pre-commit hooks and makes that more difficult with auto-fix, then we can move it to the `make stylelintdry` to warn someone of needs before the commit. But we'd have to see how much of an issue/confusion fixing it precommit would cause.

**Comment by chrispelzer** [comment]
@nickdenardis I responded in basecamp since it is a little more indepth and across other areas

**Comment by breakdancingcat** [comment]
👍🏻

**Pull request merged**
